### ISSUE TITLE
INSTALL ERROR

### ISSUE THREAD

**Issue by plumplumli** [ElNiak/QUIC-FormalVerification#48]
Ubuntu release is: `Ubuntu 20.04.6 LTS`

**Comment by plumplumli** [comment]
I encountered an issue during the compilation process(running `make` command). 
```
$ make
...
ERROR   -  mkdocstrings:
           panther.panther_worker.app.implementations.other.get-pip could not be
           found
ERROR   -  Error reading page
           'reference/panther/panther_worker/app/implementations/other/get-pip.md':
ERROR   -  Could not collect
           'panther.panther_worker.app.implementations.other.get-pip'

Aborted with a BuildError!
make: *** [Makefile:14：mkdocs] 错误 1

$ ls panther/panther_worker/app/implementations/other/
get-pip2.7.py  get-pip.py  __pycache__
```


Here are the dependencies I have already installed.
```
pre-commit
black
pymdown-extensions
mkdocs-material-extensions
mkdocs-gen-files
mkdocs-literate-nav
mkdocs-section-index
mkdocstrings[python]
mkdocs-exclude
mkdocs-same-dir
mkdocs  # static site generator for documentation in Markdown
mkdocs-material  # Material support for MkDocs
mkdocs-minify-plugin  # strips whitespaces in HTML markdown documentation pages
mkdocs-git-revision-date-localized-plugin  # displays the date of the last git modification of a markdown page
mkdocs-git-authors-plugin  # displays git authors of a markdown page
mkdocs-table-reader-plugin  # enables automatic CSV imports as a table into a markdown page
mkdocs-img2fig-plugin  # converts markdown encoded images to HTML figures
mknotebooks  # enables inclusion of Jupyter notebook in markdown page
mkdocs-awesome-pages-plugin  # enables naive configuration of page titles and their order
mkdocs-enumerate-headings-plugin  # enumerates headings across markdown pages
mkdocs-print-site-plugin  # allows visiters to File > Print > Save as PDF entire markdown documentation
mkgendocs  # generate MkDocs pages from Google-style docstrings of Python functions
markdown-callouts
mkdocs-coverage
mkdocs-material
```
Here are the commands I executed.
```
git clone https://github.com/ElNiak/PANTHER.git
git submodule update --init --recursive
pre-commit install
make
```

How to fix it? Thank you.

**Comment by pawamoy** [comment]
Try passing `-v` to the `mkdocs build/serve` command to get more logs.

**Comment by ElNiak** [comment]
Hello,

I'm sorry for the outdated documents here, this command is for the documentation generation. I am doing a big refactor with the tool's plug-and-play architecture now.

But in this version, you can build the tool with (in `tmux`):
```bash
cd panther/
python3.10 panther_cli.py --config nordsec24_config.ini build_webapp;
python3.10 panther_cli.py --config nordsec24_config.ini build_worker;
```

Then run with:
```bash
python3.10 panther_cli.py --config nordsec24_config.ini run_tools;
```

**Comment by plumplumli** [comment]
Thank you for your prompt reply. 


I found that the GitHub repository for `quant `was inaccessible, which caused the `python3.10 panther_cli.py --config nordsec24_config.ini build_worker` command to exit prematurely. The result is as follows:
![1](https://github.com/user-attachments/assets/39f6a308-d1a1-4c92-afe3-6f08b6692ccb)
Then I tried to modify the configuration file `nordsec24_config.ini`.   
```
quic_quant = False
quic_quant_vuln = False
```
It worked for me.

But I met **another problem** when running `panther_cli.py --config nordsec24_config.ini run_tools;`
![2](https://github.com/user-attachments/assets/969123d3-986a-4db3-873f-b6bccb89c893)

**Comment by plumplumli** [comment]
Thank you for your prompt reply.

I found that the GitHub repository for `quant `was inaccessible, which caused the `python3.10 panther_cli.py --config nordsec24_config.ini build_worker` command to exit prematurely. The result is as follows:
![1-1](https://github.com/user-attachments/assets/9118d4c3-c24e-4142-ae7c-6b7f2126b1fd)

Then I tried to modify the configuration file `nordsec24_config.ini`.
```
quic_quant = False
quic_quant_vuln = False
```
It worked for me.

But I met **another problem** when running `panther_cli.py --config nordsec24_config.ini run_tools;`
![2-2](https://github.com/user-attachments/assets/cd28ad54-1596-4690-b364-de020f3d62e0)

**Comment by ElNiak** [comment]
Hello,

1. For `quant`, unfortunately, NTAP closed the repository a few weeks ago. But I contacted the dev and here is his personal fork: [https://github.com/larseggert/quant](quant) if you want to see. 

You can also use wayback if you want to see old repository, e.g [http://web.archive.org/web/20220520090210/https://github.com/NTAP/quant/issues/68](http://web.archive.org/web/20220520090210/https://github.com/NTAP/quant/issues/68)

2. For x11, run this command and it should work: `xhost +local:docker`
